spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1qaz
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
  redis:
    host: 127.0.0.1
    port: 6379
  freemarker:
    template-loader-path: classpath:/       //这样写可以加载resources文件夹下所有文件,不然templates下的文件(.ftl)
                                            //无法访问static文件夹下的文件(如css,js).
    prefix: templates/                      //控制层返回时自动为返回对象加前缀

mybatis:
  mapper-locations: classpath:mapper/*.xml



