spring:
  datasource:    #采用多数据源设置
    sell:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 1qaz
      url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false #不使用"jdbc-url"会报错
      filters: stat
    slave:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 1qaz
      url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
      filters: stat
  redis:
    host: 127.0.0.1
    port: 6379
  resources:
    static-locations: classpath:/static
  mvc:
    static-path-pattern: /static/**    #不然无法访问css,js等文件

    view:
      prefix: /user/
      suffix: .jsp


wechat:
  mpAppId: wx6b58fb9ac5b1753b
  mpAppSecret: 02d7dd941e80521501d8165c357a4e34
  openAppId:  o_aHe50P-HASV-VPVbHgZfcYHgU8
  templateId: DPHJ8Uk_nJ7OgObqICuiiIPgqWrniKGiSGsE9O4W1uA
  Url: http://www.baidu.com

mybatis:
  mapper-locations: classpath:mapper/*.xml



